# dicionarios.py

def get_c170_dict(columns, index):
    return {
        '01-REG': columns[1],
        '02-NUM_ITEM': columns[2],
        '03-COD_ITEM': columns[3],
        '04-DESCR_COMPL': columns[4],
        '05-QTD': columns[5],
        '06-UNID': columns[6],
        '07-VL_ITEM': columns[7],
        '08-VL_DESC': columns[8],
        '09-IND_MOV': columns[9],
        '10-CST_ICMS': columns[10],
        '11-CFOP': columns[11],
        '12-COD_NAT': columns[12],
        '13-VL_BC_ICMS': columns[13],
        '14-ALIQ_ICMS': columns[14],
        '15-VL_ICMS': columns[15],
        '16-VL_BC_ICMS_ST': columns[16],
        '17-ALIQ_ST': columns[17],
        '18-VL_ICMS_ST': columns[18],
        '19-IND_APUR': columns[19],
        '20-CST_IPI': columns[20],
        '21-COD_ENQ': columns[21],
        '22-VL_BC_IPI': columns[22],
        '23-ALIQ_IPI': columns[23],
        '24-VL_IPI': columns[24],
        '25-CST_PIS': columns[25],
        '26-VL_BC_PIS': columns[26],
        '27-ALIQ_PIS': columns[27],
        '28-QUANT_BC_PIS': columns[28],
        '29-ALIQ_PIS_REAIS': columns[29],
        '30-VL_PIS': columns[30],
        '31-CST_COFINS': columns[31],
        '32-VL_BC_COFINS': columns[32],
        '33-ALIQ_COFINS': columns[33],
        '34-QUANT_BC_COFINS': columns[34],
        '35-ALIQ_COFINS_REAIS': columns[35],
        '36-VL_COFINS': columns[36],
        '37-COD_CTA': columns[37],
        '38-VL_ABAT_NT': columns[38],
        '39-LINHA': index
    }
def get_c100_dict(columns, index):
    # Garantir que a lista 'columns' tem pelo menos 30 elementos
    if len(columns) < 30:
        raise ValueError(f"Lista de colunas com tamanho insuficiente: esperado 30, mas obteve {len(columns)}.")

    return {
        '01-REG': columns[1],
        '02-IND_OPER': columns[2],
        '03-IND_EMIT': columns[3],
        '04-COD_PART': columns[4],
        '05-COD_MOD': columns[5],
        '06-COD_SIT': columns[6],
        '07-SER': columns[7],
        '08-NUM_DOC': columns[8],
        '09-CHV_NFE': columns[9],
        '10-DT_DOC': columns[10],
        '11-DT_E_S': columns[11],
        '12-VL_DOC': columns[12],
        '13-IND_PGTO': columns[13],
        '14-VL_DESC': columns[14],
        '15-VL_ABAT_NT': columns[15],
        '16-VL_MERC': columns[16],
        '17-IND_FRT': columns[17],
        '18-VL_FRT': columns[18],
        '19-VL_SEG': columns[19],
        '20-VL_OUT_DA': columns[20],
        '21-VL_BC_ICMS': columns[21],
        '22-VL_ICMS': columns[22],
        '23-VL_BC_ICMS_ST': columns[23],
        '24-VL_ICMS_ST': columns[24],
        '25-VL_IPI': columns[25],
        '26-VL_PIS': columns[26],
        '27-VL_COFINS': columns[27],
        '28-VL_PIS_ST': columns[28],
        '29-VL_COFINS_ST': columns[29],
        '30-LINHA': index
    }
